version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5433:5432"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-game}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-gamepass}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/game}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10

  publisher:
    container_name: publisher
    build: ./publisher
    environment:
      - PORT=8080
      - RABBIT_URL=amqp://${RABBITMQ_USER:-game}:${RABBITMQ_PASS:-gamepass}@rabbitmq:5672/%2Fgame?heartbeat=10
      - EXCHANGE=game.events
      - AUTH_TOKEN=${PUBLISHER_AUTH_TOKEN:-changeme}
      - INBUF_CAPACITY=10000
      - READINESS_MAX_BACKLOG=8000
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "8088:8080"
    
  nakama:
    container_name: nakama
    build: .
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address ${POSTGRES_ADDRESS} &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address ${POSTGRES_ADDRESS} --logger.level DEBUG --session.token_expiry_sec 7200        
    restart: always
    links:
      - "postgres:db"
    depends_on:
      postgres:
        condition: service_healthy
        
    environment:
      - PUBLISHER_AUTH_TOKEN=${PUBLISHER_AUTH_TOKEN:-changeme}
      - PUBLISHER_URL=http://publisher:8080

    volumes:
      - ./:/nakama/data
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
  rabbitmq_data:
